### ISSUE TITLE
I would like to use my own RDS password for the cluster

### ISSUE THREAD

**Issue by isen-ng** [traveloka/terraform-aws-rds-postgres#10]
As a rds admin, 
I would like to automate changing the password of my RDS cluster
because otherwise I have to resort to manually changing it, defeating the purpose of IAC

I can encrypt my the password in git using git-secret

**Comment by isen-ng** [comment]
https://github.com/traveloka/terraform-aws-rds-postgres/pull/11

**Comment by sshvetsov** [comment]
I don't this it's a good idea. Password you provide to terraform will be stored in the state file unencrypted. Git-secret doesn't apply, since you should be using remote state file, not storing your state file in Git. So rotating passwords using terraform is definitely not an ideal solution here. I would also argue that password rotation isn't IAC purpose at all. A better alternative would be to use IAC to create resources like SSM Parameter Store or Secret Manager to store and rotate your passwords.

Also note, that the root password you are creating with RDS instance should be used only as "break glass" feature. You should not use these credentials in day-to-day work. After initial rotation, put them in Last Pass and don't use them unless there's a need.

For your day-to-day needs create dedicated users with their unique credentials and set of DB privileges, each person and application must have a unique set of credentials. App might even have more then one set in some cases.

**Comment by isen-ng** [comment]
> A better alternative would be to use IAC to create resources like SSM Parameter Store or Secret Manager to store and rotate your passwords.

Ok, this is something I need to learn how to do.

> For your day-to-day needs create dedicated users with their unique credentials and set of DB privileges, each person and application must have a unique set of credentials. App might even have more then one set in some cases.

already doing that. root-user/password is used for creating new dbs and new users for the new dbs.

**Comment by isen-ng** [comment]
Agreed that because terraform stores input variable password in plain text in it's state file, providing passwords as an input variable is not a good move.

Closing

**Comment by isen-ng** [comment]
@sshvetsov 
After diving into the terraform state file discussions, the password is still stored in the state file, even if the password is randomly generated.

It's stored as an input variable and also stored as an output variable in the state file.

The only difference is that the output variable has a `sensitive` parameter that indicates that the value should not be printed into the logs. It does nothing to protect the value in state file.

All in all, the state file should be considered sensitive and should be protected from unauthorized viewing using policies. I think it might be good to have a terraform module that creates such a s3 bucket for use as terraform backend.

See discussion here:
https://github.com/hashicorp/terraform/issues/516
